---
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcoffin/armake2:2e66c92
    steps:
      - uses: actions/checkout@v4

      - name: Write secret file to disk
        env:
          DIS_BIPRIVATEKEY_B64: ${{ secrets.DIS_BIPRIVATEKEY_B64 }}
        run: |
          echo "$DIS_BIPRIVATEKEY_B64" | base64 -d > /tmp/dis.biprivatekey

      - name: Build the mod folder
        run: ./build_mod.sh /tmp/dis.biprivatekey

      - name: Upload mod as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "@DIS-Utils"
          path: "@DIS-Utils/"
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    container: steamcmd/steamcmd:ubuntu
    needs: build
    steps:
      - name: Download built mod artifact
        uses: actions/download-artifact@v4
        with:
          name: "@DIS-Utils"
          path: "@DIS-Utils"

      - name: Just Checking
        run: |
          find .
          ls -la 

#      - name: Download Wine
#        run: |
#          apt update
#          apt install -y wine64
#
#      - name: install xvfb
#        run: |
#          apt install -y xvfb
#          xvfb :0 -screen 0 1024x768x16 &
#          export DISPLAY=:0.0
#          
#      - name: Debug Wine
#        run: |
#          wine --version
#          chown -R $(whoami):$(whoami) /github/home
#          ls -la /github/

      - name: download A3Tools
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
        run: >
          steamcmd 
          "+force_install_dir /arma3"
          "+login ${STEAM_USERNAME} ${STEAM_PASSWORD}"
          "+app_update 233800"
          "+quit"

      - name: Debug A3Tools
        run: |
          find .
          ls -la /arma3/Publisher
          
      - name: uploading
        env:
          WORKSHOP_ID: ${{ secrets.WORKSHOP_ID }}
        run: |
          wine "/arma3/Publisher/PublisherCmd.exe update /id:${WORKSHOP_ID} /path:'$(pwd)/@DIS-Utils' /nologo /nosummary"


#          "+@sSteamCmdForcePlatformType windows"
# dpkg --add-architecture i386
# apt update
# apt install -y wget gnupg gnupg2 gnupg1 software-properties-common aptitude
# wget https://dl.winehq.org/wine-builds/winehq.key
# apt-key add winehq.key
# apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main'
# aptitude install winehq-stable -y

# apt install -y --install-recommends winehq-stable
#   release:
#     runs-on: ubuntu-latest
#     container: steamcmd/steamcmd:alpine-3
#     needs: build
#     steps:
#       - name: Download built mod artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: "@DIS-Utils"
#           path: "@DIS-Utils"
#       - name: Create VDF file
#         env:
#           WORKSHOP_ID: ${{ secrets.WORKSHOP_ID }}
#         run: |
#           cat <<EOF > update.vdf
#           "workshopitem"
#           {
#           "appid" "107410"
#           "publishedfileid" "${WORKSHOP_ID}"
#           "contentfolder" "$(pwd)/@DIS-Utils"
#           }
#           EOF
#       - name: Debug
#         run: |
#           cat update.vdf
#           find .
#       - name: Upload to Steam
#         env:
#           STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
#           STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
#         run: >
#           steamcmd
#           "+login ${STEAM_USERNAME} ${STEAM_PASSWORD}"
#           "+workshop_build_item $(pwd)/update.vdf"
#           "+exit"
