---
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcoffin/armake2:2e66c92
    steps:
      - uses: actions/checkout@v4

      - name: Write secret file to disk
        env:
          DIS_BIPRIVATEKEY_B64: ${{ secrets.DIS_BIPRIVATEKEY_B64 }}
        run: |
          echo "$DIS_BIPRIVATEKEY_B64" | base64 -d > /tmp/dis.biprivatekey

      - name: Build the mod folder
        run: ./build_mod.sh /tmp/dis.biprivatekey

      - name: Upload mod as artifact
        uses: actions/upload-artifact@v4
        with:
          name: "@DIS-Utils"
          path: "@DIS-Utils/"
          retention-days: 7

  release:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Download mod artifact
        uses: actions/download-artifact@v4
        with:
          name: "@DIS-Utils"
          path: "@DIS-Utils"

      - name: Debug
        run: dir @DIS-Utils
      
      - name: UploadMod
        env:
          WORKSHOP_ID: ${{ secrets.WORKSHOP_ID }}
        run: |
          'C:\Program Files (x86)\Steam\steamapps\common\Arma 3 Tools\Publisher\PublisherCmd.exe update /id:${{ secrets.WORKSHOP_ID }} /changeNote:"Auto update" /path:"@DIS-Utils"'

